general:
  show_welcome:
    type: bool
    default: true
  updates:
    check:
      type: bool
      default: true
  screenshot_dir: string
  skip_boot_anim: bool
  # throttle_io: bool
  last_viewed_menu_index: integer
  user_token: string

input:
  bindings:
    port1: string
    port2: string
    port3: string
    port4: string
  gamecontrollerdb_path: string
  auto_bind:
    type: bool
    default: true
  background_input_capture: bool

display:
  quality:
    surface_scale:
      type: integer
      default: 1
  window:
    fullscreen_on_startup: bool
    startup_size:
      type: enum
      values: [last_used, 640x480, 1280x720, 1280x800, 1280x960, 1920x1080, 2560x1440, 2560x1600, 2560x1920, 3840x2160]
      default: 1280x960
    last_width:
      type: integer
      default: 640
    last_height:
      type: integer
      default: 480
    vsync:
      type: bool
      default: true
  ui:
    show_menubar:
      type: bool
      default: true
    use_animations:
      type: bool
      default: true
    fit:
      type: enum
      values: [center, scale, scale_16_9, scale_4_3, stretch]
      default: scale
    scale:
      type: integer
      default: 1
    auto_scale:
      type: bool
      default: true

audio:
  use_dsp: bool
  volume_limit:
    type: number
    default: 1

net:
  enable: bool
  backend:
    type: enum
    values: [nat, udp, pcap]
    default: nat
  pcap:
    netif: string
  udp:
    bind_addr:
      type: string
      default: 0.0.0.0:9368
    remote_addr:
      type: string
      default: 1.2.3.4:9368
  nat:
    forward_ports:
      type: array
      items:
        host: integer
        guest: integer
        protocol:
          type: enum
          values: [tcp, udp]
          default: tcp

sys:
  mem_limit:
    type: enum
    values: ['64', '128']
    default: '64'
  avpack:
    type: enum
    values: [scart, hdtv, vga, rfu, svideo, composite, none]
    default: hdtv
  files:
    bootrom_path: string
    flashrom_path: string
    eeprom_path: string
    hdd_path: string
    dvd_path: string

perf:
  hard_fpu:
    type: bool
    default: true
  # cache_shaders:
  #   type: bool
  #   default: true
